// svelte-todo-app/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import TodoAdd from './lib/TodoAdd.svelte';
  import TodoFilter from './lib/TodoFilter.svelte';
  import TodoList from './lib/TodoList.svelte';

  let todos = [];

  function addTodo(event) {
    todos = todos.concat(event.detail);
  }

  async function fetchTodos() {
    const response = await fetch(
      'https://jsonplaceholder.typicode.com/todos?_limit=5'
    );
    const rawTodos = await response.json();
    todos = rawTodos.map((todo) => ({
      id: todo.id,
      content: todo.title,
      completed: todo.completed,
    }));
  }

  onMount(fetchTodos);

  let filter = 'all';
  let filteredTodos;

  $: {
    switch (filter) {
      case 'done':
        filteredTodos = todos.filter((todo) => todo.completed);
        break;
      case 'todo':
        filteredTodos = todos.filter((todo) => !todo.completed);
        break;
      default:
        filteredTodos = todos;
    }
  }
</script>

<main>
  <div class="container">
    <h1>欢迎使用待办列表！</h1>
    <TodoAdd tid={todos.length} on:addTodo={addTodo} />
    <TodoFilter
      selected={filter}
      on:changeFilter={(evnet) => (filter = evnet.detail)}
    />
    <TodoList todos={filteredTodos} />
  </div>
</main>

<style>
  :global(*) {
    box-sizing: border-box;
    margin: 0px;
    padding: 0px;
    font-family: Helvetica, 'PingFang SC', 'Microsoft Yahei', sans-serif;
  }

  main {
    width: 100vw;
    min-height: 100vh;
    display: grid;
    align-items: center;
    justify-items: center;
    background-color: rgb(203, 210, 240);
  }

  .container {
    width: 60%;
    max-width: 400px;
    box-shadow: 0px 0px 24px rgba(0, 0, 0, 0.15);
    border-radius: 24px;
    padding: 48px 28px;
    background-color: rgb(245, 246, 252);
  }

  h1 {
    margin: 24px 0;
    font-size: 28px;
    text-align: center;
    color: #414873;
  }
</style>

// vue-todo-app/src/App.vue
<script setup>
import TodoAdd from './components/TodoAdd.vue';
import TodoFilter from './components/TodoFilter.vue';
import TodoList from './components/TodoList.vue';
import useTodos from './composables/useTodos';
import useFilteredTodos from './composables/useFilteredTodos';

const { todos, addTodo } = useTodos();
const { filter, filteredTodos } = useFilteredTodos(todos);
</script>

<template>
  <main>
    <div class="container">
      <h1>欢迎使用待办事项！</h1>
      <todo-add :tid="todos.length" @add-todo="addTodo" />
      <todo-filter :selected="filter" @change-filter="filter = $event" />
      <todo-list :todos="filteredTodos" />
    </div>
  </main>
</template>

<style>
* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  font-family: Helvetica, 'PingFang SC', 'Microsoft Yahei', sans-serif;
}

main {
  width: 100vw;
  min-height: 100vh;
  display: grid;
  align-items: center;
  justify-items: center;
  background-color: rgb(203, 210, 240);
}

.container {
  width: 60%;
  max-width: 400px;
  box-shadow: 0px 0px 24px rgba(0, 0, 0, 0.15);
  border-radius: 24px;
  padding: 48px 28px;
  background-color: rgb(245, 246, 252);
}

h1 {
  margin: 24px 0;
  font-size: 28px;
  text-align: center;
  color: #414873;
}
</style>
