// packages/svelte-comments-app/src/lib/ReplyBox.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import CommentBox from './CommentBox.svelte';

  const dispatch = createEventDispatcher();

  let showCommentBox = false;
</script>

<button
  class="pt-4 text-blue-600 {showCommentBox ? 'pb-2' : 'pb-10'}"
  on:click={() => (showCommentBox = !showCommentBox)}
>
  回复
</button>
{#if showCommentBox}
  <CommentBox
    on:submit={(event) => dispatch('submit', event.detail)}
    on:reset={() => (showCommentBox = false)}
  />
{/if}

// packages/vue-comments-app/src/components/ReplyBox.vue
<script setup>
import { ref } from 'vue';
import CommentBox from './CommentBox.vue';

const emit = defineEmits(['submit']);
const showCommentBox = ref(false);
</script>

<template>
  <button
    class="pt-4 text-blue-600"
    :class="[showCommentBox ? 'pb-2' : 'pb-10']"
    @click="showCommentBox = !showCommentBox"
  >
    回复
  </button>
  <comment-box
    v-if="showCommentBox"
    class="mb-4"
    @submit="
      emit('submit', $event);
      showCommentBox = false;
    "
    @cancel="showCommentBox = false"
  />
</template>
