// packages/vue-todo-app/src/components/TodoList.vue
<script setup>
import TodoItem from './TodoItem.vue';

defineProps({ todos: Array });
</script>

<template>
  <div class="todo-list">
    <todo-item
      v-for="todo of todos"
      :key="todo.id"
      :todo-item="todo"
      @change-state="todo.completed = $event.target.checked"
    />
  </div>
</template>

<style scoped>
.todo-list {
  display: grid;
  row-gap: 14px;
}
</style>

// packages/svelte-todo-app/src/lib/TodoList.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import TodoItem from './TodoItem.svelte';

  const dispatch = createEventDispatcher();

  export let todos;
</script>

<div class="todo-list">
  {#each todos as todo (todo.id)}
    <TodoItem
      todoItem={todo}
      on:change-state={(event) => {
        dispatch('changeTodo', {
          id: todo.id,
          todo: { ...todo, completed: event.detail.target.checked },
        });
      }}
    />
  {/each}
</div>

<style>
  .todo-list {
    display: grid;
    row-gap: 14px;
  }
</style>
