// svelte-todo-app/src/lib/TodoItem.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  export let todoItem;
</script>

<div class="todo-item" class:done={todoItem.completed}>
  <label>
    <input
      type="checkbox"
      checked={todoItem.completed}
      on:change={(event) => dispatch('change-state', event)}
    />
    {todoItem.content}
    <span class="check-button" />
  </label>
</div>

<style>
  .todo-item {
    background: #fff;
    padding: 16px;
    border-radius: 8px;
    color: #626262;
  }

  .todo-item label {
    position: relative;
    display: flex;
    align-items: center;
  }

  .todo-item.done label {
    text-decoration: line-through;
    font-style: italic;
  }

  .todo-item label span.check-button {
    position: absolute;
    top: 0;
  }

  .todo-item label span.check-button::before,
  .todo-item label span.check-button::after {
    content: '';
    display: block;
    position: absolute;
    width: 18px;
    height: 18px;
    border-radius: 50%;
  }

  .todo-item label span.check-button::before {
    border: 1px solid #b382f9;
  }

  .todo-item label span.check-button::after {
    transition: 0.4s;
    background: #b382f9;
    transform: translate(1px, 1px) scale(0.8);
    opacity: 0;
  }

  .todo-item input {
    margin-right: 16px;
    opacity: 0;
  }

  .todo-item input:checked + span.check-button::after {
    opacity: 1;
  }
</style>

// vue-todo-app/src/components/TodoItem.vue
<script setup>
defineProps({ todoItem: Object });
defineEmits(['change-state']);
</script>

<template>
  <div :class="['todo-item', { done: todoItem.completed }]">
    <label>
      <input
        type="checkbox"
        :checked="todoItem.completed"
        @click="$emit('change-state', $event)"
      />
      {{ todoItem.content }}
      <span class="check-button"></span>
    </label>
  </div>
</template>

<style scoped>
.todo-item {
  background: #fff;
  padding: 16px;
  border-radius: 8px;
  color: #626262;
}

.todo-item label {
  position: relative;
  display: flex;
  align-items: center;
}

.todo-item.done label {
  text-decoration: line-through;
  font-style: italic;
}

.todo-item label span.check-button {
  position: absolute;
  top: 0;
}

.todo-item label span.check-button::before,
.todo-item label span.check-button::after {
  content: '';
  display: block;
  position: absolute;
  width: 18px;
  height: 18px;
  border-radius: 50%;
}

.todo-item label span.check-button::before {
  border: 1px solid #b382f9;
}

.todo-item label span.check-button::after {
  transition: 0.4s;
  background: #b382f9;
  transform: translate(1px, 1px) scale(0.8);
  opacity: 0;
}

.todo-item input {
  margin-right: 16px;
  opacity: 0;
}

.todo-item input:checked + span.check-button::after {
  opacity: 1;
}
</style>
